package lesson5;

/**

 Guess a number between 1 and 10

 Generate a secret number, and compare the number with a given (i.e. guessed) number. The user (i.e. another class) of the instantiable class GuessNumber should provide the guessed number via the setGuess() method.
 */

public class GuessNumber{
    // declare instance variables
    private int secret; // instance variable to store the number generated by the computer
    private int guess; // instance variable to store the number provided by the client/ user of this class
    private String message; // instance variable to store the message whether the two numbers are equal or one is higher than the other

    // declare constructor
    public GuessNumber(){
        // generate a random number
        // between 1 and 20
        double r1 = Math.random(); //generates a random number between [0, 1)
        double r2 = r1 * 10; // [0, 9)
        System.out.println("r2 "+ (int) r2);
        double r3 = r2 + 1; // [1, 10)
        System.out.println("r3 "+ (int) r3);
        secret = (int) r3;	// {1, 2, 3, 4, ..., 20}

        // alternatively, we could write the above statements in one single line either:
        // option 1
        // secret = (int) (Math.random()*20) + 1
        // option 2
        // secret = (int) (Math.random()*20 + 1)
    }

    // declare setters
    // setter method for the guess instance variable
    public void setGuess(int n){
        guess = n;
    }

    // declare the processing method
    public void compare(){
        if (guess == secret){
            message = "congrats";
        } else if (guess < secret ){
            message = "too low";
        } else {
            message = "too high";
        }
    }

    // declare getters
    // getter method to retrieve the message
    public String getMessage(){
        return message;
    }

    // getter method to retrieve the secret number generated by the computer
    public int getSecret(){
        return secret;
    }
}

