package lesson5;
/**
 GuessApp
 uses the instantiable class GuessNumber
 allows the user to guess a number 1 time
 */
import java.util.Scanner;
public class GuessApp {
    public static void main(String args[]){

        // declare a local variable named num to store the number provided by the user via keyboard
        int num;
        // declare a variable named input, and create an object of type Scanner
        Scanner input = new Scanner(System.in);

        // declare a variable of type GuessNumber
        GuessNumber checker;

        // create an object of type GuessNumber
        checker = new GuessNumber();


        // input
        // prompt the user to enter a number
        System.out.println("enter a number:");
        num = input.nextInt();


        // use the setter method setGuess() to assign/store in the instance variable named guess of the object checker the number provided by the user and saved in the local variable num
        checker.setGuess(num);

        // processing
        // invoke/call the method compare() on object checker to determine whether the user provided the correct number
        checker.compare();


        // output
        // retrieve the message to find out whether the user guessed the number
        // save the message in the variable called m
        String m = checker.getMessage();
        System.out.println(m);


        // retrieve the secret number (i.e the number generated by the computer)
        int s = checker.getSecret();
        System.out.println("secret: " + s);

    }  // ends main

} // ends class